[package]
name = "bdk_tmp_plan"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk_chain = {  path = "../../crates/chain", features = ["miniscript"] }

[features]
default = ["std"]
std = []
