[package]
name = "bdk_cbf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nakamoto = "0.4.0"
bdk_chain = { path = "../chain", version = "0.5.0"}
