[package]
name = "keychain_tracker_electrum_example"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk_chain = { path = "../../crates/chain", features = ["serde"] }
bdk_electrum = { path = "../../crates/electrum" }
indexed_tx_graph_example_cli = { path = "../indexed_tx_graph_example_cli"}
