[package]
name = "bdk_bench"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench"
harness = false

[dependencies]
bdk_chain = { path = "../crates/chain" }
criterion = { version = "0.5", default-features = false }
