[package]
name = "example_waterfalls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk_chain = { path = "../../crates/chain", features = ["serde"] }
bdk_waterfalls = { path = "../../crates/waterfalls", features = ["blocking"] }
example_cli = { path = "../example_cli" }
env_logger = "0.11"
