[package]
name = "keychain_tracker_rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk_chain = { path = "../../crates/chain", version = "0.3.1", features = ["serde", "miniscript"] }
bdk_rpc_wallet = { path = "../../crates/rpcwallet" }
keychain_tracker_example_cli = { path = "../keychain_tracker_example_cli" }
