name: Check Commits

on:
  pull_request:
    branches: master

jobs:
  signed-commits:
    name: Check signed commits in PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # needs the full log
          fetch-depth: 0
          # pick the pr HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check conventional commits in PR
        uses: cocogitto/cocogitto-action@v3
